name: Publish
on:
  push:
    tags:
      - r-rmd/v*
jobs:
  r-rmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Derive image tag
        id: tag
        env:
          GIT_TAG: ${{ github.ref_name }}
        run: |
          set -eux
          printf 'image=%s' "${GIT_TAG##*/}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        with:
          context: ${{ github.job }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.job }}:${{ steps.tag.outputs.image }},${{ vars.DOCKERHUB_USERNAME }}/${{ github.job }}:latest
