name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  r-rmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: r-rmd
          tags: ${{ github.job }}:${{ github.ref_name }},${{ github.job }}:latest
