name: Publish
on:
  push:
    tags:
      - r-rmd/v*
jobs:
  r-rmd:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/gidoichi/r-rmd/${{ steps.tag.outputs.image }}/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Derive image tag
        id: tag
        env:
          GIT_TAG: ${{ github.ref_name }}
        run: |
          set -eux
          printf 'image=%s' "${GIT_TAG##*/}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        id: docker
        with:
          context: r-rmd
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/r-rmd:${{ steps.tag.outputs.image }},${{ vars.DOCKERHUB_USERNAME }}/r-rmd:latest
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: |
          set -eux
          printf 'digest=%s' "${digest#sha256:}" >> "$GITHUB_OUTPUT"

  r-rmd-xpectr:
    needs: r-rmd
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/layers/gidoichi/r-rmd/${{ steps.tag.outputs.image }}-xpectr/images/sha256-${{ steps.sha256.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Derive image tag
        id: tag
        env:
          GIT_TAG: ${{ github.ref_name }}
        run: |
          set -eux
          printf 'image=%s' "${GIT_TAG##*/}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        id: docker
        with:
          build-args: "BASE_IMAGE_TAG=${{ steps.tag.outputs.image }}"
          file: r-rmd/Dockerfile-xpectr
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/r-rmd:${{ steps.tag.outputs.image }}-xpectr
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: |
          set -eux
          printf 'digest=%s' "${digest#sha256:}" >> "$GITHUB_OUTPUT"
