name: Update
on:
  schedule:
    - cron: "* 0 * * 6"
  workflow_dispatch:
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          ignore_fail: true
